Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,15 +37,15 @@ jobs:
       # 4. Install all dependencies from requirements.txt
       - name: Install dependencies
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          if [ -f "requirements.txt" ]; then
-            pip install -r requirements.txt
-          else
-            echo "requirements.txt not found!"
-            exit 1
-          fi
-
+    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  run: |
+    if [ -f "requirements.txt" ]; then
+      pip install -r requirements.txt --extra-index-url https://$GITHUB_TOKEN@github.com/TheStatsProject/mkdocs-tags.git
+    else
+      echo "requirements.txt not found!"
+      exit 1
+    fi
+    
       # 5. Lint MkDocs configuration to catch errors early
       - name: Lint MkDocs config
         run: mkdocs build --config-file mkdocs.yml --strict
